# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a259f96dc775f2dfd6401b94f8f03e03f78db01495ef59593a5ef55f4865da4e11585f1dd1b68581ff010d54a16d50fa959e208bd4206c4e1467ffeba5e9ced

test:
  secret_key_base: 8083f863c06ee176054a144c505e6fa168380b21fb337081599ad1fc2cb96509baa4003f8c601ad1535e2bc66f87d5b086cd0fb2ec510d4cf47cc048abf6cbc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
